### ISSUE TITLE
Clipboard bug with embedded files

### ISSUE THREAD

**Issue by vhk28457** [giuspen/cherrytree#86]
Version 0.36.1 on Windows 7.
It's impossible to paste copied or cutted embedded file:
```
Traceback (most recent call last):
  File "clipboard.pyc", line 98, in copy
  File "clipboard.pyc", line 162, in selection_to_clipboard
  File "exports.pyc", line 617, in selection_export_to_html
  File "exports.pyc", line 667, in get_image_html
AttributeError: 'gtk.gdk.Pixbuf' object has no attribute 'link'
```
I clearly remember that this feature worked perfectly in 0.35.10.

Small feature request: please, make option to hide pins on bookmarked nodes.

Thanks.

**Comment by giuspen** [comment]
Please try
http://www.giuspen.com/software/cherrytree_0.36.1+r1733_win32_portable.7z
and let me know

**Comment by vhk28457** [comment]
@giuspen, this version works good, thanks.
