### ISSUE TITLE
Can the glibmm-2.4 requirement be lowered?

### ISSUE THREAD

**Issue by funnelfiasco** [giuspen/cherrytree#819]
Commit [13752e1](https://github.com/giuspen/cherrytree/commit/13752e12704d256a33cb3641f9e3d268a3a3ff35#diff-04691495dd9205b6faaf73c8862e9632R85) broke builds of Cherrytree future on Fedora 31, which has glibmm-2.62.0. I've tested a build with `glibmm-2.4>=2.62` and it seems to work okay. I'm not sure what the Ubuntu 20.04 issue was, but if it's possible, can the minimum version be lowered? (I'm carrying a local patch in my spec file for the time being)

**Comment by funnelfiasco** [comment]
I think I answered my own question. My aarch64 build failed with:

` error: 'canonicalize_filename' is not a member of 'Glib'`. 

I'm guessing an x86_64 build on F31 would do the same, since that function was introduced in 2.64. I only did an F32 build of x86_64 to test locally. I'll close the issue and drop Fedora 31 from my future builds of cherrytree-future.

**Comment by giuspen** [comment]
Thanks @funnelfiasco Glib::canonicalize_filename is very useful and at the moment critical only in the Windows build but creating special cases is complicating things, I would rather give the latest Gtkmm3 to the latest distributions and maintaining anyway the Pygtk2 version for the older distributions
