### ISSUE TITLE
cherrytree c++ uses very new macOS libc++ features...only for 10.15+ at present

### ISSUE THREAD

**Issue by kencu** [giuspen/cherrytree#916]
I was working on building this with a 10.13 system I had on my lap, but there are some quite new libc++ features being asked for. The Xcode compiler (1000 series) could not handle it, so I installed llvm9, which does have the required include files, etc, but it looks like the system features on 10.13 are too old.  The general portability will be limited, as it is:
```
[ 83%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o
[ 84%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_export.cc.o
[ 84%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_file.cc.o
[ 84%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_find.cc.o
In file included from /Users/Shared/projects/cherrytree/future/src/ct/ct_actions_export.cc:24:
/Users/Shared/projects/cherrytree/future/src/ct/ct_export2html.h:98:37: error: 'path' is unavailable:
      introduced in macOS 10.15
void to_html(const std::filesystem::path& file, std::ostream& output);
                                    ^
/usr/local/opt/llvm@9/bin/../include/c++/v1/filesystem:738:24: note: 'path' has been explicitly marked
      unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
[ 85%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_format.cc.o
```

Not sure if there is a way to gear down to some fallback features if these are not available on the system.

**Comment by ForeverRainbow** [comment]
OK, well `std::filesystem::path` is not essential, strings can always be used instead. But cherrytree does need a c++17 compiler and uses some features of c++17 quite heavily

**Comment by kencu** [comment]
The libc++ implementation for macOS c++17 features has come in a bit gradually. The details are specified best in the ```__config``` header that outlines which features were available when here <https://github.com/llvm/llvm-project/blob/3d8149c2a1228609fd7d7c91a04681304a2f0ca9/libcxx/include/__config#L1424> 

It depends on your target. If you want 10.15+, no problem. If you would like to target the last 3 systems, which is kinda traditional and gets a good percentage of macOS users, then you can see there in the config file which c++17 features are available when.

**Comment by ForeverRainbow** [comment]
I think the macos version is likely to just distributed as a binary anyway, if people want to compile their own from source they should have the required toolchain.

@txe and @giuspen are better people to comment on this :p

**Comment by kencu** [comment]
Even if you compile it on 10.15, if you try to distribute it on any older systems and the system libc++ doesn't have the required symbols in it, I believe you'll get a runtime error.

**Comment by ForeverRainbow** [comment]
mmm yeah I forgot about that, its dynamically linked

**Comment by txe** [comment]
`std::filesystem` is not used widely and can be easily replaced by [glibmm file utils](https://developer.gnome.org/glibmm/stable/group__FileUtils.html) and GIO

**Comment by giuspen** [comment]
I agree with @txe we should get rid of std::filesystem and use instead glibmm, glib and gio. See also https://developer.gnome.org/glibmm/stable/group__MiscUtils.html https://developer.gnome.org/glibmm/stable/classGio_1_1File.html all indexed at https://developer.gnome.org/glibmm/stable/ and where the binding is incomplete https://developer.gnome.org/glib/stable/ and https://developer.gnome.org/gio/stable/

**Comment by txe** [comment]
I'll do it

**Comment by giuspen** [comment]
thanks @txe !

**Comment by txe** [comment]
Hi @kencu
I removed `std::filesystem` from the project, but have no opportunity to check if it is enough.
If you still have issues,  just write them down here.

**Comment by kencu** [comment]
confirming that was all it took -- builds on 10.13 using llvm-9 for compiler. Thanks!

**Comment by ForeverRainbow** [comment]
@txe Mind if I write some wrapper methods and put them in the `fs` namespace? (e.g `fs::exists` and `fs::path = std::string`)

**Comment by txe** [comment]
@ForeverRainbow, why?

**Comment by ForeverRainbow** [comment]
Because the glib methods are a bit messy with flags and such and if a paramater takes an `fs::path` its self-documenting as taking a paramater which should be a valid path instead of a random string

**Comment by ForeverRainbow** [comment]
Stuff like `directory_iterator` cannot be replicated obviously but stuff like extension checking I think should be a part of a path object (so actually maybe `fs::path` is a string with some utality functions attached)

**Comment by txe** [comment]
Actually, I'd like to have a nice wrapper for paths because I always have a hard time to remember which function to call.

You want to repeat std::filesystem approach?

**Comment by txe** [comment]
maybe @giuspen  has another opinion

**Comment by ForeverRainbow** [comment]
I was thinking just implementing the bits we need, so `fs::exists`, `fs::path` with `extension()`, `string()`, and possibly the `/` operator although I know thats a bit contriversal :p, I could also move things like the mine type checking into `fs`.

**Comment by ForeverRainbow** [comment]
of course we could always use something like [ghc::filesystem](https://github.com/gulrak/filesystem) but thats another dependency for something already done by glib :p

**Comment by kencu** [comment]
Before you do too much, as I continue to learn about this, I came across this interesting bit of information this morning <https://libcxx.llvm.org/docs/UsingLibcxx.html#using-filesystem> about how a static implementation of std::filesystem can be used for supporting older systems.

The libc++ headers still mark the symbol availability as above, so I'm not presently sure how you get around that issue. My apologies my knowledge is incomplete in this area.

**Comment by ForeverRainbow** [comment]
@kencu I found that too, I do not think that will fix it as `std::filesystem::path` was marked unavailable by a preprocessor directive, so linking to a static lib won't help

**Comment by txe** [comment]
`ghc::filesystem` looks solid, but uses wchar on windows, can be a minor issue.

@ForeverRainbow can we postpone this thing?  maybe we find a reason to use boost which comes with filesystem. then things again will have to be redone. For the time being, CtFileSystem already has some functions and can have more.

And @giuspen didn't say anything

**Comment by ForeverRainbow** [comment]
@txe Sure we can postpone it although I am more than happy to do this now even if its wasted effort later, but `wchar` is required for paths on windows by the standard so `std::filesystem` and `boost::filesystem` use it too

**Comment by giuspen** [comment]
I think if @ForeverRainbow wants to rework to the namespace fs being consistent with the namings of std:: filesystem (and boost:: filesystem where it was copied from) I'm ok with that as long as you unit test thoroughly all the methods. A future switch to std:: filesystem or boost:: filesystem would then become trivial

**Comment by ForeverRainbow** [comment]
Sure, I will refractor `CtFileSystem` and add some methods to mimic the interface of the `filesystem` std specification. I will of course add unit tests but are they necessary for simple wrappers like `exists`? 

Also I'm a woman :p

**Comment by giuspen** [comment]
She, sorry :) No for very simple there's no need unless there is a chance it won't work in the same way on multiple platforms. If it is very quick to add a test on a file or directory of tests/data, that will give us full multi platform confidence. If you work on the paths please also replace the Glib:: ustring you find on your way used on the paths. Many thanks!
